export const SliderItems = [
  {
    id: 1,
    img: require("./Assets/Sliders/Sliders img 1.svg"),
    title: "Various Category",
    description: "You can find various types of clothes on Zturf.",
    background: "#b6ffa2ac",
  },
  {
    id: 2,
    img: require("./Assets/Sliders/Sliders img 2.svg"),
    title: "Latest Trends",
    description: "Zturf provides clothes of latest ternds.",
    background: "#d1e8e2d7",
  },
  {
    id: 3,
    img: require("./Assets/Sliders/Sliders img 3.svg"),
    title: "Gender Equality",
    description: "You can find clothes for all gender on Zturf.",
    background: "#b4c0f1d1",
  },
];

export const Category = [
  {
    id: 1,
    img: require("./Assets/Categories/Sweatshirts & Hoodies.avif"),
    title: "Sweatshirts & Hoodies",
    description: "Zturf provides clothes of latest ternds.",
    background: "#d1e8e2d7",
  },
  {
    id: 2,
    img: require("./Assets/Categories/Business Apparels.avif"),
    title: "Business Apparels",
    description: "You can find various types of clothes on Zturf.",
    background: "#eee2dcd4",
  },
  {
    id: 3,
    img: require("./Assets/Categories/T-shirts.avif"),
    title: "T-shirts",
    description: "You can find clothes for all gender on Zturf.",
    background: "#c1c8e4d1",
  },
];

export const PopularProduct = [
  {
    id: 1,
    name: "Converse Shoe",
    img: require("./Assets/Popular/Converse.png"),
    wishlist: true,
    isCart: true,
    color: "brown",
    quantity: 1,
    price: 100,
    totalprice: 100,
  },
  {
    id: 2,
    name: "Half-Sweat Shirt",
    img: require("./Assets/Popular/Half-Sweat shirt.png"),
    wishlist: false,
    isCart: true,
    color: "green",
    quantity: 1,
    price: 200,
    totalprice: 200,
  },
  {
    id: 3,
    name: "Hoodie",
    img: require("./Assets/Popular/Hoodie.png"),
    wishlist: true,
    isCart: true,
    color: "blue",
    quantity: 1,
    price: 300,
    totalprice: 300,
  },
  {
    id: 4,
    name: "Jacket",
    img: require("./Assets/Popular/Jacket.png"),
    wishlist: false,
    isCart: false,
    color: "brown",
    quantity: 1,
    price: 400,
    totalprice: 400,
  },
  {
    id: 5,
    name: "Long dress",
    img: require("./Assets/Popular/Long dress.png"),
    wishlist: true,
    isCart: false,
    color: "white",
    quantity: 1,
    price: 400,
    totalprice: 400,
  },
  {
    id: 6,
    name: "Pants",
    img: require("./Assets/Popular/Pants.png"),
    wishlist: true,
    isCart: false,
    color: "black",
    quantity: 1,
    price: 500,
    totalprice: 500,
  },
  {
    id: 7,
    name: "Sweat shirt",
    img: require("./Assets/Popular/Sweat shirt.png"),
    wishlist: false,
    isCart: false,
    color: "blue",
    quantity: 1,
    price: 500,
    totalprice: 500,
  },
  {
    id: 8,
    name: "T-shirt",
    img: require("./Assets/Popular/T-shirt.png"),
    wishlist: false,
    isCart: false,
    color: "brown",
    quantity: 1,
    price: 100,
    totalprice: 100,
  },
];

export const CartItems = [
  {
    id: 1,
    name: "Converse Shoe",
    img: require("./Assets/Popular/Converse.png"),
    color: "brown",
    quantity: 1,
    size: "XL",
    price: 100,
    totalprice: 100,
  },
  {
    id: 2,
    name: "Half-Sweat Shirt",
    img: require("./Assets/Popular/Half-Sweat shirt.png"),
    color: "green",
    quantity: 2,
    size: "L",
    price: 200,
    totalprice: 400,
  },
  {
    id: 3,
    name: "Hoodie",
    img: require("./Assets/Popular/Hoodie.png"),
    color: "blue",
    quantity: 5,
    size: "S",
    price: 300,
    totalprice: 1500,
  },
];
